## Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([3,2,3,5,6])

In [3]:
a

array([3, 2, 3, 5, 6])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [19]:
mylist = [3, 2, 3, 5, 6]

mylist.append([26])
mylist[-1]

[26]

In [20]:
np.append(a, [2,3])

array([3, 2, 3, 5, 6, 2, 3])

In [24]:
np.delete(a, [1,4])

array([3, 3, 5])

In [25]:
arr = np.array([10,4,3,19,2,1,6,18])

In [26]:
np.sort(arr, )

array([ 1,  2,  3,  4,  6, 10, 18, 19])

## Shape and Size

## Creating array from Existing data

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [29]:
arr1 = arr[:5]
arr2 = arr[5:]

In [31]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12],[13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [38]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

## Copy Array

In [ ]:
a

## Basic Operations

In [39]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [42]:
v1 + v2

array([3, 5, 7])

In [43]:
v1 * v2

array([ 2,  6, 10])

In [44]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [46]:
b.sum()

6

In [47]:
b.sum(axis=1)

array([2, 4])

In [48]:
b.sum(axis=0)

array([3, 3])

In [49]:
v1 * 5

array([10, 15, 25])

In [51]:
M = np.arange(0,16).reshape(4,4)

In [52]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
M.max()

15

In [57]:
M.max(axis=0)

array([12, 13, 14, 15])

In [58]:
M.min(axis=0)

array([0, 1, 2, 3])

In [60]:
M.std()

4.6097722286464435

In [72]:
M.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

## Matrix

In [71]:
# np.ones((3,3))
# np.zeros((3,3))
np.random.random((3,3))

array([[0.40959615, 0.11411498, 0.37932748],
       [0.72603312, 0.10270242, 0.9240875 ],
       [0.98666898, 0.72296916, 0.28924599]])

In [73]:
mat = np.array([
    [1,2]
    ,[3,4]
])

In [74]:
ones = np.ones((2,2))

In [75]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [76]:
mat + 5

array([[6, 7],
       [8, 9]])